#!/usr/bin/env python3
"""
Nova Phase 5.3 — Report Assembler
Reads enriched JSONL from stdin and emits platform-ready markdown reports.
"""

import json
import os
import sys
from datetime import datetime

def severity(score: int) -> str:
    if score >= 18:
        return "Critical"
    if score >= 14:
        return "High"
    if score >= 9:
        return "Medium"
    return "Low"

def main():
    os.makedirs("reports/raw", exist_ok=True)

    for line in sys.stdin:
        r = json.loads(line)

        host = r["host"]
        path = r["path"]
        sev = severity(r.get("score", 0))
        title = f"{host}{path} – {sev} severity issue"

        poc = "\n".join(
            f"- `{cmd}`"
            for pb in r.get("playbooks", [])
            for cmd in pb.get("commands", [])
        )

        body = f"""# {title}

## Summary
Potential vulnerability identified on `{host}{path}`.

## Severity
**{sev}**

## Confidence
{r.get("confidence", 0):.2f}

## Signals
{", ".join(r.get("signals", []))}

## Description
{r.get("note", "")}

## Proof of Concept
{poc}

## Notes
- Non-destructive testing
- No authentication tokens used
- Generated by Nova
"""

        safe_name = f"{host.replace('.', '_')}{path.replace('/', '_')}.md"
        out_path = os.path.join("reports", "raw", safe_name)

        with open(out_path, "w") as f:
            f.write(body)

        print(f"[+] Report written: {out_path}")


if __name__ == "__main__":
    main()
